### ISSUE TITLE
Congrats on your interesting work! 🎉

### ISSUE THREAD

**Issue by thaoshibe** [Xiaojiu-z/Stable-Makeup.github.io#1]
Hello,
I just wanted just to say congrats on Stable-Makeup! 🎉
I've been following makeup transfer for a while and also waiting for someone to elevate it with diffusion models!
Now, here we come Stable-Makeup! Congrats again :D Hope Stable-Makeup will get accepted soon 🍀

(And congrats on SSR-Encoder as well, haha)

**Comment by YacratesWyh** [comment]
Good Job!

**Comment by Xiaojiu-z** [comment]
> Hello, I just wanted just to say congrats on Stable-Makeup! 🎉 I've been following makeup transfer for a while and also waiting for someone to elevate it with diffusion models! Now, here we come Stable-Makeup! Congrats again :D Hope Stable-Makeup will get accepted soon 🍀
> 
> (And congrats on SSR-Encoder as well, haha)

Thank you for your very positive comments on our work 😄😄. A lot of your wonderful work is very inspiring to us～～
